default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
