---
:concurrency: 1

:pidfile: tmp/pids/sidekiq.pid

development:
  :concurrency: 1

staging:
  :concurrency: 1

production:
  :concurrency: 1


:queues:
  - [critical  ,  10]
  - [single    ,  1]
  - [default   ,  3]
