---
:concurrency: 3
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 3
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical   , 10]
  - [default    , 5]
  - [low        , 1]
